package wallet

//----------------------------------------------------------------------
// This file is part of Gospel.
// Copyright (C) 2011-2020 Bernd Fix
//
// Gospel is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License,
// or (at your option) any later version.
//
// Gospel is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL3.0-or-later
//----------------------------------------------------------------------

// CoinSpec defines a BIP44 registered coin.
// (see https://github.com/satoshilabs/slips/blob/master/slip-0044.md)
type CoinSpec struct {
	ID     int
	Symbol string
	Name   string
}

var (
	// CoinList of all all available BIP44 coin types
	CoinList = []*CoinSpec{
		{0, "BTC", "Bitcoin"},
		{2, "LTC", "Litecoin"},
		{3, "DOGE", "Dogecoin"},
		{4, "RDD", "Reddcoin"},
		{5, "DSH", "Dash (ex Darkcoin)"},
		{6, "PPC", "Peercoin"},
		{7, "NMC", "Namecoin"},
		{8, "FTC", "Feathercoin"},
		{9, "XCP", "Counterparty"},
		{10, "BLK", "Blackcoin"},
		{11, "NSR", "NuShares"},
		{12, "NBT", "NuBits"},
		{13, "MZC", "Mazacoin"},
		{14, "VIA", "Viacoin"},
		{15, "XCH", "ClearingHouse"},
		{16, "RBY", "Rubycoin"},
		{17, "GRS", "Groestlcoin"},
		{18, "DGC", "Digitalcoin"},
		{19, "CCN", "Cannacoin"},
		{20, "DGB", "DigiByte"},
		{22, "MONA", "Monacoin"},
		{23, "CLAM", "Clams"},
		{24, "XPM", "Primecoin"},
		{25, "NEOS", "Neoscoin"},
		{26, "JBS", "Jumbucks"},
		{27, "ZRC", "ziftrCOIN"},
		{28, "VTC", "Vertcoin"},
		{29, "NXT", "NXT"},
		{30, "BURST", "Burst"},
		{31, "MUE", "MonetaryUnit"},
		{32, "ZOOM", "Zoom"},
		{33, "VASH", "Virtual Cash Also known as VPNcoin"},
		{34, "CDN", "Canada eCoin"},
		{35, "SDC", "ShadowCash"},
		{36, "PKB", "ParkByte"},
		{37, "PND", "Pandacoin"},
		{38, "START", "StartCOIN"},
		{39, "MOIN", "MOIN"},
		{40, "EXP", "Expanse"},
		{41, "EMC2", "Einsteinium"},
		{42, "DCR", "Decred"},
		{43, "XEM", "NEM"},
		{44, "PART", "Particl"},
		{45, "ARG", "Argentum"},
		{48, "SHR", "Shreeji"},
		{49, "GCR", "Global Currency Reserve (GCRcoin)"},
		{50, "NVC", "Novacoin"},
		{51, "AC", "Asiacoin"},
		{52, "BTCD", "Bitcoindark"},
		{53, "DOPE", "Dopecoin"},
		{54, "TPC", "Templecoin"},
		{55, "AIB", "AIB"},
		{56, "EDRC", "EDRCoin"},
		{57, "SYS", "Syscoin"},
		{58, "SLR", "Solarcoin"},
		{59, "SMLY", "Smileycoin"},
		{60, "ETH", "Ether"},
		{61, "ETC", "Ether Classic"},
		{62, "PSB", "Pesobit"},
		{63, "LDCN", "Landcoin"},
		{65, "XBC", "Bitcoinplus"},
		{66, "IOP", "Internet of People"},
		{67, "NXS", "Nexus"},
		{68, "INSN", "InsaneCoin"},
		{69, "OK", "OKCash"},
		{70, "BRIT", "BritCoin"},
		{71, "CMP", "Compcoin"},
		{72, "CRW", "Crown"},
		{73, "BELA", "BelaCoin"},
		{75, "FJC", "FujiCoin"},
		{76, "MIX", "MIX"},
		{77, "XVG", "Verge"},
		{78, "EFL", "Electronic Gulden"},
		{79, "CLUB", "ClubCoin"},
		{80, "RICHX", "RichCoin"},
		{81, "POT", "Potcoin"},
		{82, "QRK", "Quarkcoin"},
		{83, "TRC", "Terracoin"},
		{84, "GRC", "Gridcoin"},
		{85, "AUR", "Auroracoin"},
		{86, "IXC", "IXCoin"},
		{87, "NLG", "Gulden"},
		{88, "BITB", "BitBean"},
		{89, "BTA", "Bata"},
		{90, "XMY", "Myriadcoin"},
		{91, "BSD", "BitSend"},
		{92, "UNO", "Unobtanium"},
		{93, "MTR", "MasterTrader"},
		{94, "GB", "GoldBlocks"},
		{95, "SHM", "Saham"},
		{96, "CRX", "Chronos"},
		{97, "BIQ", "Ubiquoin"},
		{98, "EVO", "Evotion"},
		{99, "STO", "SaveTheOcean"},
		{100, "BIGUP", "BigUp"},
		{101, "GAME", "GameCredits"},
		{102, "DLC", "Dollarcoins"},
		{103, "ZYD", "Zayedcoin"},
		{104, "DBIC", "Dubaicoin"},
		{105, "STRAT", "Stratis"},
		{106, "SH", "Shilling"},
		{107, "MARS", "MarsCoin"},
		{108, "UBQ", "Ubiq"},
		{109, "PTC", "Pesetacoin"},
		{110, "NRO", "Neurocoin"},
		{111, "ARK", "ARK"},
		{112, "USC", "UltimateSecureCashMain"},
		{113, "THC", "Hempcoin"},
		{114, "LINX", "Linx"},
		{115, "ECN", "Ecoin"},
		{116, "DNR", "Denarius"},
		{117, "PINK", "Pinkcoin"},
		{118, "PIGGY", "PiggyCoin"},
		{119, "PIVX", "Pivx"},
		{120, "FLASH", "Flashcoin"},
		{121, "ZEN", "Zencash"},
		{122, "PUT", "Putincoin"},
		{123, "ZNY", "BitZeny"},
		{124, "UNIFY", "Unify"},
		{125, "XST", "StealthCoin"},
		{126, "BRK", "Breakout Coin"},
		{127, "VC", "Vcash"},
		{128, "XMR", "Monero"},
		{129, "VOX", "Voxels"},
		{130, "NAV", "NavCoin"},
		{131, "FCT", "Factom Factoids"},
		{132, "EC", "Factom Entry Credits"},
		{133, "ZEC", "Zcash"},
		{134, "LSK", "Lisk"},
		{135, "STEEM", "Steem"},
		{136, "XZC", "ZCoin"},
		{137, "SBTC", "RSK"},
		{139, "RPT", "RealPointCoin"},
		{140, "LBC", "LBRY Credits"},
		{141, "KMD", "Komodo"},
		{142, "BSQ", "bisq Token"},
		{143, "RIC", "Riecoin"},
		{144, "XRP", "Ripple"},
		{145, "BCH", "Bitcoin Cash"},
		{146, "NEBL", "Neblio"},
		{147, "ZCL", "ZClassic"},
		{148, "XLM", "Stellar Lumens"},
		{149, "NLC2", "NoLimitCoin2"},
		{150, "WHL", "WhaleCoin"},
		{151, "ERC", "EuropeCoin"},
		{152, "DMD", "Diamond"},
		{153, "BTM", "Bytom"},
		{154, "BIO", "Biocoin"},
		{155, "XWC", "Whitecoin"},
		{156, "BTG", "Bitcoin Gold"},
		{157, "BTC2X", "Bitcoin 2x"},
		{158, "SSN", "SuperSkynet"},
		{159, "TOA", "TOACoin"},
		{160, "BTX", "Bitcore"},
		{161, "ACC", "Adcoin"},
		{162, "BCO", "Bridgecoin"},
		{163, "ELLA", "Ellaism"},
		{164, "PIRL", "Pirl"},
		{165, "XRB", "RaiBlocks"},
		{166, "VIVO", "Vivo"},
		{167, "FRST", "Firstcoin"},
		{168, "HNC", "Helleniccoin"},
		{169, "BUZZ", "BUZZ"},
		{170, "MBRS", "Ember"},
		{171, "HSR", "Hcash"},
		{172, "HTML", "HTMLCOIN"},
		{173, "ODN", "Obsidian"},
		{174, "ONX", "OnixCoin"},
		{175, "RVN", "Ravencoin"},
		{176, "GBX", "GoByte"},
		{177, "BTCZ", "BitcoinZ"},
		{178, "POA", "Poa"},
		{179, "NYC", "NewYorkCoin"},
		{180, "MXT", "MarteXcoin"},
		{181, "WC", "Wincoin"},
		{182, "MNX", "Minexcoin"},
		{183, "BTCP", "Bitcoin Private"},
		{184, "MUSIC", "Musicoin"},
		{185, "BCA", "Bitcoin Atom"},
		{186, "CRAVE", "Crave"},
		{187, "STAK", "STRAKS"},
		{188, "WBTC", "World Bitcoin"},
		{189, "LCH", "LiteCash"},
		{190, "EXCL", "ExclusiveCoin"},
		{192, "LCC", "LitecoinCash"},
		{193, "XFE", "Feirm"},
		{194, "EOS", "EOS"},
		{195, "TRX", "Tron"},
		{196, "KOBO", "Kobocoin"},
		{197, "HUSH", "HUSH"},
		{198, "BANANO", "Bananos"},
		{199, "ETF", "ETF"},
		{200, "OMNI", "Omni"},
		{201, "BIFI", "BitcoinFile"},
		{202, "UFO", "Uniform Fiscal Object"},
		{203, "CNMC", "Cryptonodes"},
		{204, "NRG", "Energi"},
		{205, "RIN", "Ringo"},
		{206, "ATP", "PlatON"},
		{207, "EVT", "everiToken"},
		{208, "ATN", "ATN"},
		{209, "BIS", "Bismuth"},
		{210, "NEET", "NEETCOIN"},
		{211, "BOPO", "BopoChain"},
		{212, "OOT", "Utrum"},
		{215, "BOXY", "BoxyCoin"},
		{216, "FLO", "Flo"},
		{222, "BITG", "Bitcoin Green"},
		{223, "ASK", "AskCoin"},
		{224, "SMART", "Smartcash"},
		{225, "XUEZ", "XUEZ"},
		{226, "HLM", "Helium"},
		{233, "VAR", "Varda"},
		{242, "NIM", "Nimiq"},
		{247, "UC", "Ulord"},
		{250, "SOOM", "Soom"},
		{253, "NPW", "NewPowerCoin"},
		{256, "NANO", "Bitcoin Nano"},
		{257, "BTCC", "Bitcoin Core"},
		{259, "ZEST", "Zest"},
		{270, "ONE", "ONE"},
		{271, "SBC", "SBC"},
		{299, "NUKO", "Nekonium"},
		{300, "GNX", "Genaro Network"},
		{312, "ARA", "Aura"},
		{321, "RAP", "Rapture"},
		{328, "BLOCK", "Blocknet"},
		{333, "MEM", "MemCoin"},
		{425, "AION", "Aion"},
		{444, "PHR", "Phore"},
		{510, "KOTO", "Koto"},
		{512, "XRD", "Radiant"},
		{528, "YAP", "Yapstone"},
		{555, "BCS", "Bitcoin Smart"},
		{625, "EAST", "Eastcoin"},
		{666, "ACT", "Achain"},
		{668, "SSC", "SelfSell"},
		{777, "BTW", "Bitcoin World"},
		{800, "BEET", "Beetle Coin"},
		{801, "DST", "DSTRA"},
		{808, "QVT", "Qvolta"},
		{818, "VET", "VeChain Token"},
		{820, "CLO", "Callisto"},
		{886, "ADF", "AD Token"},
		{888, "NEO", "NEO"},
		{890, "XSEL", "Seln"},
		{998, "LBTC", "Lightning Bitcoin"},
		{999, "BCD", "Bitcoin Diamond"},
		{1000, "BTN", "Bitcoin New"},
		{1002, "BKT", "BanKitt"},
		{1024, "ONT", "Ontology"},
		{1111, "BBC", "Big Bitcoin"},
		{1122, "CMT", "CyberMiles Token"},
		{1128, "ETSC", "Ethereum Social"},
		{1145, "CDY", "Bitcoin Candy"},
		{1337, "DFC", "Defcoin"},
		{1397, "HYC", "Hycon"},
		{1620, "ATH", "Atheios"},
		{1688, "BCX", "BitcoinX"},
		{1729, "XTZ", "Tezos"},
		{1815, "ADA", "Cardano"},
		{1856, "TES", "Teslacoin"},
		{1901, "CLC", "Classica"},
		{1919, "VIPS", "VIPSTARCOIN"},
		{1977, "XMX", "Xuma"},
		{1987, "EGEM", "EtherGem"},
		{1989, "HODL", "HOdlcoin"},
		{1990, "PHL", "Placeholders"},
		{1997, "POLIS", "Polis"},
		{2018, "EOSC", "EOSClassic"},
		{2301, "QTUM", "QTUM"},
		{2302, "ETP", "Metaverse"},
		{2303, "GXC", "GXChain"},
		{2304, "SSC", "SelfSell"},
		{2305, "ELA", "Elastos"},
		{2570, "AOA", "Aurora"},
		{3552, "DEO", "Destocoin"},
		{2718, "NAS", "Nebulas"},
		{3377, "ROI", "ROIcoin"},
		{4218, "IOTA", "IOTA"},
		{4242, "AXE", "Axe"},
		{5248, "FIC", "FIC"},
		{6060, "GO", "GoChain GO"},
		{6666, "BPA", "Bitcoin Pizza"},
		{6688, "SAFE", "SAFE"},
		{6969, "ROGER", "TheHolyrogerCoin"},
		{7777, "BTV", "Bitvote"},
		{8339, "BTQ", "BitcoinQuark"},
		{8888, "SBTC", "Super Bitcoin"},
		{8999, "BTP", "Bitcoin Pay"},
		{9888, "BTF", "Bitcoin Faith"},
		{9999, "GOD", "Bitcoin God"},
		{10291, "BTR", "Bitcoin Rhodium"},
		{22504, "PWR", "PWRcoin"},
		{31102, "ESN", "EtherSocial Network"},
		{33878, "BTCS", "Bitcoin Stake"},
		{37310, "RSK", "Testnet"},
		{65536, "KETH", "Krypton World"},
		{99999, "WICC", "Waykichain"},
		{200625, "AKA", "Akroma"},
		{424242, "X42", "x42"},
		{1313114, "ETHO", "Ether-1"},
		{1712144, "LAX", "LAPO"},
		{5249353, "BCO", "BitcoinOre"},
		{5249354, "BHD", "BitcoinHD"},
		{5718350, "WAN", "Wanchain"},
		{5741564, "WAVES", "Waves"},
		{91927009, "kUSD", "kUSD"},
	}
)
